name: p04
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_0
  - backcall=0.1.0=py_0
  - bleach=2.1.3=py_0
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - html5lib=1.0.1=py_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.3.1=py36_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.32.1=py36_0
  - jupyterlab_launcher=0.10.5=py36_0
  - libsodium=1.0.16=0
  - markupsafe=1.0=py36_0
  - mistune=0.8.3=py36_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - notebook=5.4.1=py36_0
  - openssl=1.0.2o=0
  - pandoc=2.1.3=0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.0=py_0
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - pygments=2.2.0=py36_0
  - python-dateutil=2.7.2=py_0
  - pyzmq=17.0.0=py36_4
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - zeromq=4.2.5=1
  - bzip2=1.0.6=hd86a083_4
  - cffi=1.11.5=py36h342bebf_0
  - cmake=3.9.4=h30c3106_0
  - curl=7.59.0=ha441bb4_0
  - expat=2.2.5=hb8e80ba_0
  - intel-openmp=2018.0.0=8
  - libcurl=7.59.0=hf30b1f0_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libssh2=1.8.0=h322a93b_4
  - libuv=1.20.0=h1de35cc_0
  - mkl=2018.0.2=1
  - mkl-include=2018.0.2=1
  - mkl_fft=1.0.1=py36h917ab60_0
  - mkl_random=1.0.1=py36h78cc56f_0
  - ncurses=6.0=hd04f020_2
  - nose=1.3.7=py36h73fae2b_2
  - numpy=1.14.2=py36ha9ae307_1
  - pip=10.0.1=py36_0
  - pycparser=2.18=py36h724b2fc_1
  - python=3.6.5=hc167b69_1
  - pyyaml=3.12=py36h2ba1e63_1
  - readline=7.0=hc1231fa_4
  - rhash=1.3.5=h3aa0507_1
  - setuptools=39.0.1=py36_0
  - sqlite=3.23.1=hf1716c9_0
  - tk=8.6.7=h35a86e2_3
  - typing=3.6.4=py36_0
  - wheel=0.31.0=py36_0
  - xz=5.2.3=h727817e_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - absl-py==0.2.0
    - astor==0.6.2
    - gast==0.2.0
    - grpcio==1.11.0
    - markdown==2.6.11
    - pillow==5.1.0
    - protobuf==3.5.2.post1
    - tensorboard==1.8.0
    - tensorboardx==1.2
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - torch==0.4.0a0+200fb22
    - torchvision==0.2.1
    - werkzeug==0.14.1
prefix: /Users/leemeng/anaconda3/envs/p04

